### ISSUE TITLE
Is it possible to pass a custom (raw) query to the configuration ?

### ISSUE THREAD

**Issue by thejoelinux** [allanmcarvalho/DataTables#30]
Hi,

I can't find how to pass a custom query (a direct select with some complex join conditions) to the createConfig function of the plugin.

I've tried to make associations, but I want to associate a table with itself and make the binding with a custom value, which is apparently impossible to do with CakePHP ORM.

Thanks for your help,

**Comment by allanmcarvalho** [comment]
In Query ORM object probably you will do it. I don't know how now, but in some methods you can pass a more complex options using callback params. But in this version of plugin, I believe that is not possible, because all the configuration and params of query that the user can use, is in on array format.

In the new version, you will able to use the Query object format.

But to answer your question, I already created very complex queries in cake, with very specific rules. So, is possible!

**Comment by thejoelinux** [comment]
Thanks for your answer. I will ask for help on the official CakePHP support forum, because that one almost drive me mad. ORM is cool but when you lose *hours* to make a query that really took like 1 minute to write in plain SQL... not to mention the fact that once it is done, it's not easy to understand what's going on if you're not the author (and even if you were) :)

**Comment by thejoelinux** [comment]
My solution was to use a custom finder; and some help on the issue :)

https://stackoverflow.com/questions/61381433/cakephp-orm-query-with-a-join-on-the-same-table-with-a-non-standard-associatio/61384941

But somehow, the datas came out as an array ? Don't know what went wrong, but still, it works.
